[package]
name = "i3_time_tracker"
version = "0.1.0"
authors = ["Geoffrey Irons <sdfgeoff@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
i3ipc="0.10"
log="0.4"
rusqlite="0.21"
time="0.2.7"
